import type { Community, Profile } from "./types";

export const DEMO_COMMUNITY: Community = {
  id: "00000000-0000-4000-8000-000000000001",
  name: "Builder Hive",
  type: "founder_community",
  city: "San Francisco",
  description:
    "A trusted demo network of founders, builders, mentors, investors, and operators building early-stage companies.",
};

const defaultPermissions = {
  can_talk_to_agents: true,
  can_recommend_people: true,
  can_draft_messages: true,
  can_send_without_approval: false,
  can_share_phone: false,
  can_share_email: false,
  can_schedule_meetings: false,
  can_discuss_finances: false,
  can_discuss_professional: true,
};

export const SEED_PROFILES: Profile[] = [
  {
    id: "maya",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Maya Chen",
    city: "San Francisco",
    profession: "Founder",
    company: "Lumen AI",
    role: "Founder",
    stage: "Pre-seed",
    bio: "Building AI onboarding tools for B2B SaaS teams. Looking for design partners and founder peers.",
    avatar_color: "from-purple-400 to-pink-400",
    interests: ["AI", "B2B SaaS", "Product strategy", "Design partners", "Coffee"],
    skills: ["Product", "Customer discovery", "AI/ML"],
    goals: ["customers", "feedback", "peer_support"],
    current_ask: "Find design partners who can give feedback on onboarding analytics.",
    offering: "Can share early-stage founder lessons and AI product feedback.",
    availability: "Two 30-minute calls per week",
    likes: "Clear asks, thoughtful product feedback, founder walks",
    dislikes: "Vague networking with no next step",
    topics_enjoy: "AI UX, onboarding, early customers, product-led growth",
    topics_avoid: "Cold sales pitches",
    agent: {
      agent_name: "Maya Agent",
      tone: "Warm",
      agent_intro:
        "I represent Maya, a pre-seed founder building AI onboarding tools for B2B SaaS teams.",
      current_mission: "Find design partners and founder peers inside Builder Hive.",
      status: "active",
      memory: [
        "Needs feedback from B2B SaaS teams with onboarding problems.",
        "Prefers specific intro context and a clear first conversation topic.",
        "Can help other founders with AI product positioning.",
      ],
    },
    permissions: defaultPermissions,
  },
  {
    id: "jordan",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Jordan Lee",
    city: "San Francisco",
    profession: "AI Engineer",
    company: "Stealth",
    role: "Builder",
    stage: "Idea validation",
    bio: "AI infrastructure engineer exploring a developer-tools startup and looking for a product-minded cofounder.",
    avatar_color: "from-emerald-400 to-teal-400",
    interests: ["AI", "Developer tools", "Engineering", "AI agents", "Startups"],
    skills: ["Engineering", "AI/ML", "Developer relations"],
    goals: ["cofounders", "feedback", "peer_support"],
    current_ask: "Meet product-minded founders who understand developer workflows.",
    offering: "Can help with AI architecture, evaluation, and technical scoping.",
    availability: "Evenings and Friday afternoons",
    likes: "Structured cofounder conversations and technical depth",
    dislikes: "Idea-only meetings without user evidence",
    topics_enjoy: "AI infra, evals, developer experience, startup formation",
    topics_avoid: "Speculative crypto",
    agent: {
      agent_name: "Jordan Agent",
      tone: "Direct",
      agent_intro: "I represent Jordan, an AI engineer validating a developer-tools startup.",
      current_mission: "Find a product-minded cofounder and useful technical founder peers.",
      status: "active",
      memory: [
        "Open to cofounder conversations if there is clear product curiosity.",
        "Can review AI architecture and eval plans.",
        "Prefers short, structured intro calls.",
      ],
    },
    permissions: { ...defaultPermissions, can_schedule_meetings: true },
  },
  {
    id: "sofia",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Sofia Alvarez",
    city: "San Francisco",
    profession: "Product Designer",
    company: "Figma",
    role: "Mentor",
    stage: "Advisor",
    bio: "Product design mentor helping early teams improve onboarding, activation, and design systems.",
    avatar_color: "from-sky-400 to-indigo-400",
    interests: ["Design", "Product strategy", "B2B SaaS", "Mentorship", "AI"],
    skills: ["Design", "Product", "Customer discovery"],
    goals: ["mentorship", "feedback", "advisors"],
    current_ask: "Meet founders who need sharp UX feedback and can act on it quickly.",
    offering: "Can give practical feedback on onboarding flows, design systems, and AI UX.",
    availability: "One mentor coffee per week",
    likes: "Screenshots, prototypes, and specific product questions",
    dislikes: "Generic portfolio reviews",
    topics_enjoy: "Activation, AI UX, design systems, founder taste",
    topics_avoid: "Unpaid long-term consulting asks",
    agent: {
      agent_name: "Sofia Agent",
      tone: "Warm",
      agent_intro: "I represent Sofia, a product design mentor for early startup teams.",
      current_mission: "Find founders who need practical onboarding and AI UX feedback.",
      status: "active",
      memory: [
        "Best intros include a prototype or concrete UX question.",
        "Happy to mentor serious early founders.",
        "Avoids vague advisory asks.",
      ],
    },
    permissions: { ...defaultPermissions, can_schedule_meetings: true },
  },
  {
    id: "nina",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Nina Patel",
    city: "San Francisco",
    profession: "Seed Investor",
    company: "Northstar Ventures",
    role: "Investor",
    stage: "Seed",
    bio: "Seed investor focused on B2B AI, workflow automation, and vertical software.",
    avatar_color: "from-rose-400 to-red-400",
    interests: ["Investing", "B2B SaaS", "AI agents", "Go-to-market", "Operations"],
    skills: ["Fundraising", "Sales", "Finance"],
    goals: ["fundraising", "advisors", "partnerships"],
    current_ask: "Meet founders with clear customer pull in B2B AI or vertical software.",
    offering: "Can give fundraising feedback and make operator/advisor intros when there is fit.",
    availability: "Selective office hours",
    likes: "Traction evidence, customer insight, crisp fundraising narratives",
    dislikes: "Mass investor blasts",
    topics_enjoy: "Market wedge, distribution, founder-market fit",
    topics_avoid: "Investment advice framed as guarantees",
    agent: {
      agent_name: "Nina Agent",
      tone: "Professional",
      agent_intro: "I represent Nina, a seed investor focused on B2B AI and vertical software.",
      current_mission: "Surface high-context founder conversations and advisor opportunities.",
      status: "active",
      memory: [
        "Only recommend investor intros when the founder has a clear ask.",
        "Avoid making investment promises.",
        "Prefers concise context and traction signals.",
      ],
    },
    permissions: defaultPermissions,
  },
  {
    id: "omar",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Omar Williams",
    city: "Oakland",
    profession: "Growth Operator",
    company: "Formerly Ramp",
    role: "Operator",
    stage: "Scale-up",
    bio: "Growth and revenue operator helping technical founders turn early usage into repeatable pipeline.",
    avatar_color: "from-amber-400 to-orange-400",
    interests: ["Growth", "Go-to-market", "B2B SaaS", "Operations", "Startups"],
    skills: ["Sales", "Marketing", "Operations"],
    goals: ["advisors", "customers", "hiring"],
    current_ask: "Meet technical founders who need help turning early users into pipeline.",
    offering: "Can review GTM experiments, landing pages, and outbound motion.",
    availability: "Office hours every other Thursday",
    likes: "Metrics, customer segments, fast experiments",
    dislikes: "Growth hacks without a real ICP",
    topics_enjoy: "GTM, activation, pricing, sales motion",
    topics_avoid: "Spammy outbound",
    agent: {
      agent_name: "Omar Agent",
      tone: "Direct",
      agent_intro:
        "I represent Omar, a growth operator who helps technical founders build repeatable pipeline.",
      current_mission: "Find founders who need GTM help and can use tactical feedback.",
      status: "paused",
      memory: [
        "Strong fit for founders with early usage but weak pipeline.",
        "Can give tactical GTM feedback.",
        "Prefers metrics and a clear ICP.",
      ],
    },
    permissions: { ...defaultPermissions, can_schedule_meetings: true },
  },
  {
    id: "elena",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Elena Rossi",
    city: "San Francisco",
    profession: "Founder",
    company: "CareLoop",
    role: "Founder",
    stage: "Seed",
    bio: "Healthcare workflow founder looking for operator mentors and design partners in clinics.",
    avatar_color: "from-cyan-400 to-blue-500",
    interests: ["Healthcare", "Operations", "B2B SaaS", "Design partners", "AI"],
    skills: ["Product", "Operations", "Customer discovery"],
    goals: ["customers", "mentorship", "advisors"],
    current_ask: "Find healthcare operators who can react to a clinic workflow prototype.",
    offering: "Can share healthcare customer-discovery lessons and workflow research.",
    availability: "Early mornings or lunchtime",
    likes: "Domain experts, practical workflow details, thoughtful pilots",
    dislikes: "Generic healthcare takes",
    topics_enjoy: "Clinical operations, workflow automation, compliance-aware product",
    topics_avoid: "Medical advice",
    agent: {
      agent_name: "Elena Agent",
      tone: "Professional",
      agent_intro:
        "I represent Elena, a healthcare workflow founder looking for operators and design partners.",
      current_mission: "Find healthcare operators, mentors, and design partners.",
      status: "active",
      memory: [
        "Needs practical workflow feedback from healthcare operators.",
        "Avoids medical advice and unsupported clinical claims.",
        "Can help other founders with regulated-market discovery.",
      ],
    },
    permissions: defaultPermissions,
  },
  {
    id: "priya",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Priya Shah",
    city: "San Francisco",
    profession: "Founder",
    company: "LedgerLoop",
    role: "Founder",
    stage: "Pre-seed",
    bio: "Building finance ops automation for seed-stage startups that are outgrowing spreadsheets.",
    avatar_color: "from-fuchsia-400 to-violet-500",
    interests: ["Fintech", "Operations", "B2B SaaS", "AI agents", "Fundraising"],
    skills: ["Finance", "Product", "Operations"],
    goals: ["customers", "fundraising", "advisors"],
    current_ask:
      "Meet finance operators at seed-stage companies who can react to an AI bookkeeping workflow.",
    offering: "Can help founders think through finance ops, pricing, and early fundraising prep.",
    availability: "Tuesday and Thursday mornings",
    likes: "Specific workflow pain, messy spreadsheets, practical pilot criteria",
    dislikes: "Abstract fintech brainstorming",
    topics_enjoy: "Finance ops, agentic workflows, pricing, seed fundraising",
    topics_avoid: "Personal financial advice",
    agent: {
      agent_name: "Priya Agent",
      tone: "Professional",
      agent_intro:
        "I represent Priya, a fintech founder building finance automation for early startups.",
      current_mission: "Find finance operators, design partners, and fundraising advisors.",
      status: "active",
      memory: [
        "Needs finance operators who feel spreadsheet pain weekly.",
        "Can give practical fundraising and finance ops feedback.",
        "Avoids personal financial advice.",
      ],
    },
    permissions: defaultPermissions,
  },
  {
    id: "marcus",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Marcus Reed",
    city: "Berkeley",
    profession: "Developer Advocate",
    company: "Formerly Supabase",
    role: "Advisor",
    stage: "Advisor",
    bio: "Developer relations advisor helping devtool startups earn trust with technical communities.",
    avatar_color: "from-lime-400 to-emerald-500",
    interests: ["Developer tools", "Developer relations", "Community", "Engineering", "Startups"],
    skills: ["Developer relations", "Community", "Marketing"],
    goals: ["advisors", "partnerships", "feedback"],
    current_ask: "Meet technical founders who need honest feedback on developer adoption and docs.",
    offering: "Can review launch plans, docs, community strategy, and developer onboarding.",
    availability: "One advisory session every Friday",
    likes: "Strong technical products with unclear developer adoption",
    dislikes: "Communities treated as acquisition channels only",
    topics_enjoy: "Devrel, docs, open source launches, community trust",
    topics_avoid: "Vanity launch metrics",
    agent: {
      agent_name: "Marcus Agent",
      tone: "Direct",
      agent_intro: "I represent Marcus, a developer relations advisor for technical startup teams.",
      current_mission: "Find devtool founders who need practical developer adoption feedback.",
      status: "paused",
      memory: [
        "Best fit is technical founders building for developers.",
        "Can review docs, launch plans, and community strategy.",
        "Prefers concrete products over vague platform ideas.",
      ],
    },
    permissions: { ...defaultPermissions, can_schedule_meetings: true },
  },
  {
    id: "rachel",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Rachel Kim",
    city: "San Mateo",
    profession: "People Operator",
    company: "Formerly Notion",
    role: "Operator",
    stage: "Scale-up",
    bio: "Early people and operations leader helping founders make their first ten hires intentionally.",
    avatar_color: "from-orange-300 to-rose-500",
    interests: ["Operations", "Hiring", "Community", "Startups", "Product strategy"],
    skills: ["Operations", "Customer discovery", "Marketing"],
    goals: ["hiring", "mentorship", "advisors"],
    current_ask: "Meet founders preparing for their first operator or founding team hires.",
    offering:
      "Can help with role design, interview loops, onboarding, and early operating rhythms.",
    availability: "Two founder office-hour slots per month",
    likes: "Founders who want a deliberate team design, not just more headcount",
    dislikes: "Urgent hiring without clear ownership",
    topics_enjoy: "First hires, operating cadence, onboarding, founder communication",
    topics_avoid: "Compensation promises",
    agent: {
      agent_name: "Rachel Agent",
      tone: "Warm",
      agent_intro: "I represent Rachel, an early people and operations leader for startup teams.",
      current_mission: "Find founders who need help designing early roles and operating cadence.",
      status: "active",
      memory: [
        "Strong fit for founders hiring their first operators.",
        "Can help with role design and onboarding.",
        "Avoids compensation or hiring guarantees.",
      ],
    },
    permissions: defaultPermissions,
  },
  {
    id: "kenji",
    community_id: DEMO_COMMUNITY.id,
    full_name: "Kenji Tanaka",
    city: "San Francisco",
    profession: "Climate Founder",
    company: "GridPilot",
    role: "Founder",
    stage: "Seed",
    bio: "Climate software founder building tools for distributed energy project operations.",
    avatar_color: "from-teal-300 to-cyan-600",
    interests: ["Climate", "Operations", "B2B SaaS", "Partnerships", "AI"],
    skills: ["Product", "Sales", "Operations"],
    goals: ["partnerships", "customers", "peer_support"],
    current_ask: "Meet energy project operators and B2B founders selling into operational teams.",
    offering: "Can share climate customer discovery lessons and enterprise pilot structure.",
    availability: "Wednesday afternoons",
    likes: "Operational buyers, pilot structure, practical sales lessons",
    dislikes: "Climate takes without customer detail",
    topics_enjoy: "Energy operations, pilots, climate SaaS, enterprise sales",
    topics_avoid: "Policy debates without product implications",
    agent: {
      agent_name: "Kenji Agent",
      tone: "Curious",
      agent_intro:
        "I represent Kenji, a climate software founder building for energy operations teams.",
      current_mission: "Find operators, partnerships, and founder peers in climate and B2B SaaS.",
      status: "active",
      memory: [
        "Needs operators with direct project management pain.",
        "Can help with climate customer discovery and pilot structure.",
        "Prefers practical GTM conversations.",
      ],
    },
    permissions: defaultPermissions,
  },
];

export function getSeedProfile(id: string) {
  return SEED_PROFILES.find((p) => p.id === id);
}
